export const abi = [
 
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_proposalFee",
               "type":"uint256"
            },
            {
               "internalType":"uint256",
               "name":"_votingFee",
               "type":"uint256"
            },
            {
               "internalType":"uint256",
               "name":"_timePoint",
               "type":"uint256"
            },
            {
               "internalType":"uint256",
               "name":"_proposalID",
               "type":"uint256"
            },
            {
               "internalType":"address",
               "name":"sabreDAOAddress",
               "type":"address"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"constructor"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"owner",
               "type":"address"
            }
         ],
         "name":"OwnableInvalidOwner",
         "type":"error"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"account",
               "type":"address"
            }
         ],
         "name":"OwnableUnauthorizedAccount",
         "type":"error"
      },
      {
         "inputs":[
            
         ],
         "name":"ProposalFee_notCorrect",
         "type":"error"
      },
      {
         "inputs":[
            
         ],
         "name":"SBRState_notCorrect",
         "type":"error"
      },
      {
         "inputs":[
            
         ],
         "name":"SBRinvalidSupportError",
         "type":"error"
      },
      {
         "inputs":[
            
         ],
         "name":"SabreDAO_noEnoughToken",
         "type":"error"
      },
      {
         "inputs":[
            
         ],
         "name":"SabreDAO_notAnHolder",
         "type":"error"
      },
      {
         "inputs":[
            
         ],
         "name":"currentVaultStatusError",
         "type":"error"
      },
      {
         "inputs":[
            
         ],
         "name":"invalidProposalIDError",
         "type":"error"
      },
      {
         "inputs":[
            
         ],
         "name":"proposalExecuteError",
         "type":"error"
      },
      {
         "inputs":[
            
         ],
         "name":"s_vaultTimePostError",
         "type":"error"
      },
      {
         "inputs":[
            
         ],
         "name":"voteFee_notCorrect",
         "type":"error"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":true,
               "internalType":"address",
               "name":"investor",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"proposalID",
               "type":"uint256"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"amount",
               "type":"uint256"
            }
         ],
         "name":"Investment",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":true,
               "internalType":"address",
               "name":"previousOwner",
               "type":"address"
            },
            {
               "indexed":true,
               "internalType":"address",
               "name":"newOwner",
               "type":"address"
            }
         ],
         "name":"OwnershipTransferred",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":true,
               "internalType":"address",
               "name":"buyer",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"amount",
               "type":"uint256"
            }
         ],
         "name":"buyer",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"address",
               "name":"targets",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"values",
               "type":"uint256"
            },
            {
               "indexed":false,
               "internalType":"bytes",
               "name":"calldatas",
               "type":"bytes"
            },
            {
               "indexed":false,
               "internalType":"string",
               "name":"description",
               "type":"string"
            }
         ],
         "name":"en_Proposer",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"proposalId",
               "type":"uint256"
            },
            {
               "indexed":false,
               "internalType":"uint8",
               "name":"support",
               "type":"uint8"
            },
            {
               "indexed":false,
               "internalType":"string",
               "name":"reason",
               "type":"string"
            }
         ],
         "name":"ev_Voter",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"address",
               "name":"unstaker",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"amount",
               "type":"uint256"
            }
         ],
         "name":"ev_claimAndUnstaker",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"address",
               "name":"getStakerAmount",
               "type":"address"
            }
         ],
         "name":"ev_getStakeAmount",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"address",
               "name":"staker",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"amount",
               "type":"uint256"
            }
         ],
         "name":"ev_stake",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":true,
               "internalType":"address",
               "name":"refunder",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"proposalID",
               "type":"uint256"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"amount",
               "type":"uint256"
            }
         ],
         "name":"refund",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"enum SabreDAOEngine.vault_State",
               "name":"newState",
               "type":"uint8"
            }
         ],
         "name":"vaultStatusChanged",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"proposalId",
               "type":"uint256"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"_duration",
               "type":"uint256"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"amountToRefund",
               "type":"uint256"
            }
         ],
         "name":"vaultduration",
         "type":"event"
      },
      {
         "inputs":[
            {
               "internalType":"address[]",
               "name":"targets",
               "type":"address[]"
            },
            {
               "internalType":"uint256[]",
               "name":"values",
               "type":"uint256[]"
            },
            {
               "internalType":"bytes[]",
               "name":"calldatas",
               "type":"bytes[]"
            },
            {
               "internalType":"string",
               "name":"description",
               "type":"string"
            }
         ],
         "name":"Propose",
         "outputs":[
            
         ],
         "stateMutability":"payable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"SBRDAOGovernorPro",
         "outputs":[
            {
               "internalType":"contract SabreDAOGovernorPro",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"SBRDAO_State",
         "outputs":[
            {
               "internalType":"enum SabreDAOEngine.SabreDAO_State",
               "name":"",
               "type":"uint8"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"SBRSStaking",
         "outputs":[
            {
               "internalType":"contract SabreDAOStaking",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"TimePoint",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"Vault_State",
         "outputs":[
            {
               "internalType":"enum SabreDAOEngine.vault_State",
               "name":"",
               "type":"uint8"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"Vote_State",
         "outputs":[
            {
               "internalType":"enum SabreDAOEngine.vote_State",
               "name":"",
               "type":"uint8"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"account",
               "type":"address"
            },
            {
               "internalType":"uint256",
               "name":"timePoint",
               "type":"uint256"
            }
         ],
         "name":"_getBalanceAtTime",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "name":"a_projectProposer",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"amountToBuy",
               "type":"uint256"
            }
         ],
         "name":"buy",
         "outputs":[
            
         ],
         "stateMutability":"payable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"amountToUnstake",
               "type":"uint256"
            }
         ],
         "name":"claimAndUnstake",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"claimReward",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_proposalID",
               "type":"uint256"
            },
            {
               "internalType":"uint256",
               "name":"_AmountToReFund",
               "type":"uint256"
            }
         ],
         "name":"ends_VaultInvest",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"getCurrentVaultStatus",
         "outputs":[
            {
               "internalType":"enum SabreDAOEngine.vault_State",
               "name":"",
               "type":"uint8"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"investor",
               "type":"address"
            }
         ],
         "name":"getParticipationAmount",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"staker",
               "type":"address"
            }
         ],
         "name":"getStakeAmount",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"getTotalStakedAmount",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_propposalID",
               "type":"uint256"
            }
         ],
         "name":"getVaultDuration",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"last_TimePoint",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"proposalID",
               "type":"uint256"
            }
         ],
         "name":"m_Proposals",
         "outputs":[
            {
               "internalType":"string",
               "name":"_description",
               "type":"string"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"user",
               "type":"address"
            }
         ],
         "name":"m_SabreDAOBuy",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"amount",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"proposalID",
               "type":"uint256"
            }
         ],
         "name":"m_executions",
         "outputs":[
            {
               "internalType":"string",
               "name":"_description",
               "type":"string"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"proposalID",
               "type":"uint256"
            },
            {
               "internalType":"address",
               "name":"investor",
               "type":"address"
            }
         ],
         "name":"m_vaultsInvest",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"investAmount",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"proposalID",
               "type":"uint256"
            }
         ],
         "name":"m_votes",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"_proposalId",
               "type":"uint256"
            },
            {
               "internalType":"uint8",
               "name":"_support",
               "type":"uint8"
            },
            {
               "internalType":"string",
               "name":"_reason",
               "type":"string"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"owner",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "name":"proposalExecuted",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"proposalID",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"proposeFee",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"renounceOwnership",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"returnS_vaultProposalAndVoteData",
         "outputs":[
            {
               "components":[
                  {
                     "internalType":"uint256",
                     "name":"proposalId",
                     "type":"uint256"
                  },
                  {
                     "internalType":"address[]",
                     "name":"targets",
                     "type":"address[]"
                  },
                  {
                     "internalType":"uint256[]",
                     "name":"values",
                     "type":"uint256[]"
                  },
                  {
                     "internalType":"bytes[]",
                     "name":"calldatas",
                     "type":"bytes[]"
                  },
                  {
                     "internalType":"string",
                     "name":"description",
                     "type":"string"
                  },
                  {
                     "internalType":"uint8",
                     "name":"support",
                     "type":"uint8"
                  },
                  {
                     "internalType":"string",
                     "name":"reason",
                     "type":"string"
                  }
               ],
               "internalType":"struct SabreDAOEngine.proposeAndVoteData[]",
               "name":"",
               "type":"tuple[]"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_proposalID",
               "type":"uint256"
            },
            {
               "internalType":"address",
               "name":"user",
               "type":"address"
            }
         ],
         "name":"returnUSERPROFILE",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"s_vault",
         "outputs":[
            {
               "internalType":"contract S_vault",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_proposalID",
               "type":"uint256"
            },
            {
               "internalType":"uint256",
               "name":"AmountToInvest",
               "type":"uint256"
            }
         ],
         "name":"s_vaultInvest",
         "outputs":[
            
         ],
         "stateMutability":"payable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_proposalID",
               "type":"uint256"
            },
            {
               "internalType":"uint256",
               "name":"_AmountToReFund",
               "type":"uint256"
            }
         ],
         "name":"s_vaultRefund",
         "outputs":[
            
         ],
         "stateMutability":"payable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_proposalID",
               "type":"uint256"
            }
         ],
         "name":"s_vaultTransferFundToTarget",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"sabreDAO",
         "outputs":[
            {
               "internalType":"contract SabreDAO",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"setVaultStatus",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_proposalID",
               "type":"uint256"
            },
            {
               "internalType":"uint256",
               "name":"Duration",
               "type":"uint256"
            },
            {
               "internalType":"uint256",
               "name":"_amountToRefund",
               "type":"uint256"
            }
         ],
         "name":"setVaultTimePoint_Duration",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"amount",
               "type":"uint256"
            }
         ],
         "name":"stake",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "name":"totalInvestmentAmounts",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"newOwner",
               "type":"address"
            }
         ],
         "name":"transferOwnership",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"amount",
               "type":"uint256"
            }
         ],
         "name":"unStake",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "name":"vaultDurations",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"proposalId",
               "type":"uint256"
            },
            {
               "internalType":"uint8",
               "name":"support",
               "type":"uint8"
            },
            {
               "internalType":"string",
               "name":"reason",
               "type":"string"
            }
         ],
         "name":"vote",
         "outputs":[
            
         ],
         "stateMutability":"payable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"votingFee",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      }
   
] as const